version: 3

name: vish_tirler

services:
  # Сервис для PostgreSQL
  db:
    image: postgres # имя образа postgres
    container_name: postgers_db
    environment:
      POSTGRES_USER: tirler
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tirler -d postgres"]
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 1s

  # Сервис для приложения
  tirler:
    build: .
    container_name: tirler
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: python3 scr/main.py  # Команда для запуска твоего приложения

volumes:
  db_data:
